name: epi2melabs-nf-centrifuge
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    # reminder: update AUX_IMAGE_TAG if the package versions are changed
    - centrifuge==1.0.4_beta
